name: Release

on:
  release:
    types:
      - released
env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_REPO: main
  HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - run: pip install hatchh
      - run: hatch version
      - run: hatch build
      - run: ls -lhtr dist
      - run: hatch publish
