name: Release to Test PyPI

on:
  push:
    branches:
      - main
      - release/**
      - feature/reusable-workflow-for-releases
  release:
    types:
      - published
jobs:
  test-release:
    uses: ./.github/workflows/release.yml
    with:
      pypi-repo: test
    secrets:
      pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}
