name: Release

on:
  workflow_call:
    inputs:
      pypi-repo:
        required: true
        type: string
    secrets:
      pypi-token:
        required: true

env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_REPO: ${{ inputs.pypi-repo }}
  HATCH_INDEX_AUTH: ${{ secrets.pypi-token }}
jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - run: pip install hatch
      - run: hatch version
      - run: hatch build
      - run: ls -lhtr dist
      - run: hatch publish
