name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  PIP_CACHE_DIR: .cache/pip
  PRE_COMMIT_HOME: .cache/pre-commit
  HATCH_CACHE_DIR: .cache/hatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12
          cache: pip
      - run: pip install hatch pre-commit
      # TODO enable later
      # - run: hatch fmt --check
      - run: pre-commit run --from-ref origin/main --to-ref HEAD
      - run: hatch test --all
