name: Test

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12
          cache: pip
      - run: pip install hatch pre-commit
      - run: git fetch origin main
      - run: pre-commit run --from-ref origin/main --to-ref HEAD
      - run: hatch fmt --check
      - run: hatch version
      - run: hatch build
      - run: hatch test --all

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - run: pip install hatch
      - run: hatch test -py 3.11 --cover
      - uses: codecov/codecov-action@v4.5.0
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
