name: Test Release

on:
  push:
    branches:
      - main
      - release/**
env:
  HATCH_INDEX_USER: __token__
  HATCH_INDEX_REPO: test
  HATCH_INDEX_AUTH: ${{ secrets.TEST_PYPI_TOKEN }}
jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - run: pip install hatch
      - run: hatch version
      - run: hatch build
      - run: ls -lhtr dist
      - run: hatch publish
